In [1]:
import sagemaker
print(sagemaker.__version__)
print(sagemaker.Session)

AttributeError: module 'sagemaker' has no attribute '__version__'

In [1]:
%pip install --upgrade sagemaker

Collecting sagemaker
  Using cached sagemaker-3.15.0-py3-none-any.whl.metadata (20 kB)
Collecting sagemaker-core<3.0.0,>=2.14.0 (from sagemaker)
  Using cached sagemaker_core-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting sagemaker-train<2.0.0,>=1.14.0 (from sagemaker)
  Using cached sagemaker_train-1.15.0-py3-none-any.whl.metadata (8.2 kB)
Collecting sagemaker-serve<2.0.0,>=1.14.0 (from sagemaker)
  Using cached sagemaker_serve-1.15.0-py3-none-any.whl.metadata (14 kB)
Collecting sagemaker-mlops<2.0.0,>=1.14.0 (from sagemaker)
  Using cached sagemaker_mlops-1.15.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: boto3<2.0.0,>=1.42.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.42.97)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.13.4)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (6.0.3)
Requirement already satisfied: jsonschema<5.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.23.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.10.0)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.0.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (6.10.0)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.15.0)
Requirement already satisfied: pytz>=2021.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2024.2)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.34.2)
Requirement already satisfied: attrs>=20.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (26.1.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (25.0)
Requirement already satisfied: protobuf<7.0.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (6.31.1)
Requirement already satisfied: pandas>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.3.3)
Requirement already satisfied: numpy>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.26.4)
Requirement already satisfied: smdebug_rulesconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.0.1)
Requirement already satisfied: schema>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.7.7)
Requirement already satisfied: omegaconf>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.3.0)
Requirement already satisfied: scipy>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.16.3)
Requirement already satisfied: cloudpickle>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (3.1.2)
Requirement already satisfied: paramiko>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (5.0.0)
Requirement already satisfied: tblib>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (3.2.2)
Requirement already satisfied: cryptography>=46.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.14.0->sagemaker) (46.0.7)
Requirement already satisfied: botocore<1.43.0,>=1.42.97 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.42.97)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.16.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.97->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.97->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.26.20)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.4.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.97->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (3.17)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2026.5.20)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2.20.0)
Requirement already satisfied: pyiceberg>=0.8.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.14.0->sagemaker) (0.11.1)
Requirement already satisfied: pyarrow>=14.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.14.0->sagemaker) (21.0.0)
Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.14.0->sagemaker) (2026.3.0)
Requirement already satisfied: deepdiff in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (9.1.0)
Requirement already satisfied: mlflow in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.11.1)
Requirement already satisfied: sagemaker_schema_inference_artifacts in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.0.5)
Requirement already satisfied: pytest in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (9.0.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (4.68.2)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (5.9.8)
Requirement already satisfied: tritonclient[http] in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.41.1)
Requirement already satisfied: onnx in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.20.0)
Requirement already satisfied: onnxruntime in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.26.0)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.8.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.14.0->sagemaker) (3.4.3)
Requirement already satisfied: jinja2<4.0,>=3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.14.0->sagemaker) (3.1.6)
Requirement already satisfied: sagemaker-mlflow<1.0.0,>=0.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.14.0->sagemaker) (0.3.0)
Requirement already satisfied: nest_asyncio>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.14.0->sagemaker) (1.6.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.14.0->sagemaker) (3.2.11)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.14.0->sagemaker) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<4.0,>=3.0->sagemaker-train<2.0.0,>=1.14.0->sagemaker) (3.0.3)
Requirement already satisfied: Flask-CORS<7 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (6.0.5)
Requirement already satisfied: Flask<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.1.3)
Requirement already satisfied: aiohttp<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.18.4)
Requirement already satisfied: cachetools<8,>=5.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (8.2.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.116.0)
Requirement already satisfied: docker<8,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (7.1.0)
Requirement already satisfied: fastapi<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.1.50)
Requirement already satisfied: gunicorn<26 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (23.0.0)
Requirement already satisfied: huey<3,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.6.0)
Requirement already satisfied: matplotlib<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.10.9)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.42.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.42.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.42.1)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.2.2)
Requirement already satisfied: scikit-learn<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.7.2)
Requirement already satisfied: skops<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.0.50)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.5.0)
Requirement already satisfied: uvicorn<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.46.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.24.2)
Requirement already satisfied: Mako in /opt/conda/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.3.12)
Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.12/site-packages (from cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (1.17.1)
Requirement already satisfied: google-auth~=2.0 in /opt/conda/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.53.0)
Requirement already satisfied: starlette>=0.46.0 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.3.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (2.2.0)
Requirement already satisfied: werkzeug>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.5.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.63b1 in /opt/conda/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.63b1)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.6.0)
Collecting prettytable>=3.9 (from skops<1->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker)
  Using cached prettytable-3.18.0-py3-none-any.whl.metadata (37 kB)
Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (3.5.1)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn<1->mlflow->sagemaker-serve<2.0.0,>=1.14.0->sagemaker) (0.16.0)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=1.14->cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (3.0)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (0.1.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf>=2.1.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (4.9.3)
Requirement already satisfied: bcrypt>=3.2 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (5.0.0)
Requirement already satisfied: invoke>=2.0 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.14.0->sagemaker) (3.0.3)

In [1]:
import sagemaker
print(sagemaker.__version__)
print(sagemaker.Session)

AttributeError: module 'sagemaker' has no attribute '__version__'

In [2]:
import sagemaker

print(sagemaker.__version__)
print(sagemaker.Session)

AttributeError: module 'sagemaker' has no attribute '__version__'

In [3]:
import sagemaker

print("SageMaker module:", sagemaker)
print("Has Session:", hasattr(sagemaker, "Session"))
print("Version:", getattr(sagemaker, "__version__", "Not Found"))

SageMaker module: <module 'sagemaker' from '/opt/conda/lib/python3.12/site-packages/sagemaker/__init__.py'>
Has Session: False
Version: Not Found

In [4]:
%pip uninstall -y sagemaker sagemaker-core sagemaker-mlops sagemaker-train sagemaker-serve
%pip install --force-reinstall "sagemaker<3"

Found existing installation: sagemaker 3.15.0
Uninstalling sagemaker-3.15.0:
  Successfully uninstalled sagemaker-3.15.0
Found existing installation: sagemaker-core 2.15.0
Uninstalling sagemaker-core-2.15.0:
  Successfully uninstalled sagemaker-core-2.15.0
Found existing installation: sagemaker-mlops 1.15.0
Uninstalling sagemaker-mlops-1.15.0:
  Successfully uninstalled sagemaker-mlops-1.15.0
Found existing installation: sagemaker-train 1.15.0
Uninstalling sagemaker-train-1.15.0:
  Successfully uninstalled sagemaker-train-1.15.0
Found existing installation: sagemaker-serve 1.15.0
Uninstalling sagemaker-serve-1.15.0:
  Successfully uninstalled sagemaker-serve-1.15.0
Note: you may need to restart the kernel to use updated packages.
Collecting sagemaker<3
  Downloading sagemaker-2.257.3-py3-none-any.whl.metadata (17 kB)
Collecting attrs<26,>=24 (from sagemaker<3)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting boto3<2.0,>=1.42.2 (from sagemaker<3)
  Downloading boto3-1.43.40-py3-none-any.whl.metadata (6.6 kB)
Collecting cloudpickle>=2.2.1 (from sagemaker<3)
  Downloading cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting docker (from sagemaker<3)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting fastapi (from sagemaker<3)
  Downloading fastapi-0.139.0-py3-none-any.whl.metadata (26 kB)
Collecting google-pasta (from sagemaker<3)
  Downloading google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting graphene<4,>=3 (from sagemaker<3)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting importlib-metadata<7.0,>=1.4.0 (from sagemaker<3)
  Downloading importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)
Collecting jsonschema (from sagemaker<3)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting numpy<3.0,>=1.26.4 (from sagemaker<3)
  Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting omegaconf<3,>=2.2 (from sagemaker<3)
  Downloading omegaconf-2.3.1-py3-none-any.whl.metadata (4.5 kB)
Collecting packaging<25,>=23.0 (from sagemaker<3)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pandas>=2.3.0 (from sagemaker<3)
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pathos (from sagemaker<3)
  Downloading pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs (from sagemaker<3)
  Downloading platformdirs-4.10.0-py3-none-any.whl.metadata (5.5 kB)
Collecting protobuf<7.0,>=3.12 (from sagemaker<3)
  Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting psutil (from sagemaker<3)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting pyyaml>=6.0.1 (from sagemaker<3)
  Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests (from sagemaker<3)
  Downloading requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3)
  Downloading sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Collecting schema (from sagemaker<3)
  Downloading schema-0.7.8-py2.py3-none-any.whl.metadata (34 kB)
Collecting smdebug-rulesconfig==1.0.1 (from sagemaker<3)
  Downloading smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl.metadata (943 bytes)
Collecting tblib<4,>=1.7.0 (from sagemaker<3)
  Downloading tblib-3.2.2-py3-none-any.whl.metadata (27 kB)
Collecting tqdm (from sagemaker<3)
  Downloading tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Collecting urllib3<3.0.0,>=1.26.8 (from sagemaker<3)
  Downloading urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting uvicorn (from sagemaker<3)
  Downloading uvicorn-0.49.0-py3-none-any.whl.metadata (6.7 kB)
Collecting botocore<1.44.0,>=1.43.40 (from boto3<2.0,>=1.42.2->sagemaker<3)
  Downloading botocore-1.43.40-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2.0,>=1.42.2->sagemaker<3)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2.0,>=1.42.2->sagemaker<3)
  Downloading s3transfer-0.19.0-py3-none-any.whl.metadata (1.7 kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.44.0,>=1.43.40->boto3<2.0,>=1.42.2->sagemaker<3)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Collecting typing-extensions<5,>=4.7.1 (from graphene<4,>=3->sagemaker<3)
  Downloading typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting zipp>=0.5 (from importlib-metadata<7.0,>=1.4.0->sagemaker<3)
  Downloading zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<3,>=2.2->sagemaker<3)
  Downloading antlr4-python3-runtime-4.9.3.tar.gz (117 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.44.0,>=1.43.40->boto3<2.0,>=1.42.2->sagemaker<3)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting pydantic<3.0.0,>=2.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting rich<15.0.0,>=13.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Collecting mock<5.0,>4.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading mock-4.0.3-py3-none-any.whl.metadata (2.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->sagemaker<3)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema->sagemaker<3)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema->sagemaker<3)
  Downloading rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Downloading mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting charset_normalizer<4,>=2 (from requests->sagemaker<3)
  Downloading charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests->sagemaker<3)
  Downloading idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting certifi>=2023.5.7 (from requests->sagemaker<3)
  Downloading certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting starlette>=0.46.0 (from fastapi->sagemaker<3)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting annotated-doc>=0.0.2 (from fastapi->sagemaker<3)
  Downloading annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting anyio<5,>=3.6.2 (from starlette>=0.46.0->fastapi->sagemaker<3)
  Downloading anyio-4.14.1-py3-none-any.whl.metadata (4.6 kB)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3)
  Downloading ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Collecting dill>=0.4.1 (from pathos->sagemaker<3)
  Downloading dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pox>=0.3.7 (from pathos->sagemaker<3)
  Downloading pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Collecting multiprocess>=0.70.19 (from pathos->sagemaker<3)
  Downloading multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting click>=7.0 (from uvicorn->sagemaker<3)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting h11>=0.8 (from uvicorn->sagemaker<3)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Downloading sagemaker-2.257.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 51.4 MB/s  0:00:00
Downloading smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl (20 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading boto3-1.43.40-py3-none-any.whl (140 kB)
Downloading botocore-1.43.40-py3-none-any.whl (15.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.3/15.3 MB 91.6 MB/s  0:00:00
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Downloading importlib_metadata-6.11.0-py3-none-any.whl (23 kB)
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 107.2 MB/s  0:00:00
Downloading omegaconf-2.3.1-py3-none-any.whl (79 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
Downloading protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading s3transfer-0.19.0-py3-none-any.whl (90 kB)
Downloading sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading mock-4.0.3-py3-none-any.whl (28 kB)
Downloading platformdirs-4.10.0-py3-none-any.whl (22 kB)
Downloading pydantic-2.13.4-py3-none-any.whl (472 kB)
Downloading pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 185.2 MB/s  0:00:00
Downloading pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 73.8 MB/s  0:00:00
Downloading rich-14.3.4-py3-none-any.whl (310 kB)
Downloading pygments-2.20.0-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 90.3 MB/s  0:00:00
Downloading tblib-3.2.2-py3-none-any.whl (12 kB)
Downloading typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Downloading urllib3-2.7.0-py3-none-any.whl (131 kB)
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 123.0 MB/s  0:00:00
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (366 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Downloading zipp-4.1.0-py3-none-any.whl (10 kB)
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
Downloading requests-2.34.2-py3-none-any.whl (73 kB)
Downloading charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (216 kB)
Downloading idna-3.18-py3-none-any.whl (65 kB)
Downloading certifi-2026.6.17-py3-none-any.whl (133 kB)
Downloading fastapi-0.139.0-py3-none-any.whl (130 kB)
Downloading annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Downloading starlette-1.3.1-py3-none-any.whl (73 kB)
Downloading anyio-4.14.1-py3-none-any.whl (124 kB)
Downloading google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading pathos-0.3.5-py3-none-any.whl (82 kB)
Downloading dill-0.4.1-py3-none-any.whl (120 kB)
Downloading multiprocess-0.70.19-py312-none-any.whl (150 kB)
Downloading pox-0.3.7-py3-none-any.whl (29 kB)
Downloading ppft-1.7.8-py3-none-any.whl (56 kB)
Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Downloading schema-0.7.8-py2.py3-none-any.whl (19 kB)
Downloading tqdm-4.68.3-py3-none-any.whl (78 kB)
Downloading uvicorn-0.49.0-py3-none-any.whl (71 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Building wheels for collected packages: antlr4-python3-runtime
  Building wheel for antlr4-python3-runtime (pyproject.toml) ... done
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.9.3-py3-none-any.whl size=144590 sha256=d1392ae89dc390cf1d0c8298d6af6f1bf7cf8aa68833c743fe3b13392f6c4b0a
  Stored in directory: /home/sagemaker-user/.cache/pip/wheels/1f/be/48/13754633f1d08d1fbfc60d5e80ae1e5d7329500477685286cd
Successfully built antlr4-python3-runtime
Installing collected packages: schema, antlr4-python3-runtime, zipp, urllib3, typing-extensions, tqdm, tblib, smdebug-rulesconfig, six, rpds-py, pyyaml, pygments, psutil, protobuf, ppft, pox, platformdirs, packaging, numpy, mock, mdurl, jmespath, idna, h11, graphql-core, dill, cloudpickle, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, uvicorn, typing-inspection, requests, referencing, python-dateutil, pydantic-core, omegaconf, multiprocess, markdown-it-py, importlib-metadata, graphql-relay, google-pasta, anyio, starlette, rich, pydantic, pathos, pandas, jsonschema-specifications, graphene, docker, botocore, s3transfer, jsonschema, fastapi, boto3, sagemaker-core, sagemaker
  Attempting uninstall: schema
    Found existing installation: schema 0.7.7
    Uninstalling schema-0.7.7:
      Successfully uninstalled schema-0.7.7━━━━━  0/61 [schema]
  Attempting uninstall: antlr4-python3-runtime0m  0/61 [schema]
    Found existing installation: antlr4-python3-runtime 4.9.30m [schema]
    Uninstalling antlr4-python3-runtime-4.9.3:0m  0/61 [schema]
      Successfully uninstalled antlr4-python3-runtime-4.9.3 [schema]
  Attempting uninstall: zipp━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
    Found existing installation: zipp 4.1.0━━━━━━━━━━  1/61 [antlr4-python3-runtime]
    Uninstalling zipp-4.1.0:━━━━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
      Successfully uninstalled zipp-4.1.0━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
  Attempting uninstall: urllib3━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
    Found existing installation: urllib3 1.26.20━━━━━  1/61 [antlr4-python3-runtime]
    Uninstalling urllib3-1.26.20:━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
      Successfully uninstalled urllib3-1.26.20━━━━━━━  1/61 [antlr4-python3-runtime]
  Attempting uninstall: typing-extensions━━━━━━━━━━━━━━━━━━━━━━━━━  3/61 [urllib3]e]
    Found existing installation: typing_extensions 4.15.0━━━━━  3/61 [urllib3]
    Uninstalling typing_extensions-4.15.0:━━━━━━━━━━━━━━━━━━━━  3/61 [urllib3]
      Successfully uninstalled typing_extensions-4.15.0━━━━━━━━━━━  4/61 [typing-extensions]
  Attempting uninstall: tqdm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]
    Found existing installation: tqdm 4.68.2━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]tensions]
    Uninstalling tqdm-4.68.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
      Successfully uninstalled tqdm-4.68.2━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
  Attempting uninstall: tblib━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
    Found existing installation: tblib 3.2.2━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
    Uninstalling tblib-3.2.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
      Successfully uninstalled tblib-3.2.2━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
  Attempting uninstall: smdebug-rulesconfig━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
    Found existing installation: smdebug-rulesconfig 1.0.1━━━━  5/61 [tqdm]
    Uninstalling smdebug-rulesconfig-1.0.1:━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
      Successfully uninstalled smdebug-rulesconfig-1.0.1━━━━━━  5/61 [tqdm]
  Attempting uninstall: six[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/61 [smdebug-rulesconfig]
    Found existing installation: six 1.17.0━━━━━━━━━━━━━━━━━━━  7/61 [smdebug-rulesconfig]
    Uninstalling six-1.17.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/61 [smdebug-rulesconfig]
      Successfully uninstalled six-1.17.0━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]rulesconfig]
  Attempting uninstall: rpds-py━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
    Found existing installation: rpds-py 0.27.1━━━━━━━━━━━━━━━  8/61 [six]
    Uninstalling rpds-py-0.27.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
      Successfully uninstalled rpds-py-0.27.1━━━━━━━━━━━━━━━━━  8/61 [six]
  Attempting uninstall: pyyaml━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
    Found existing installation: PyYAML 6.0.3━━━━━━━━━━━━━━━━━  8/61 [six]
    Uninstalling PyYAML-6.0.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
      Successfully uninstalled PyYAML-6.0.3━━━━━━━━━━━━━━━━━━━  8/61 [six]
  Attempting uninstall: pygmentsm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/61 [pyyaml]
    Found existing installation: Pygments 2.20.0━━━━━━━━━━━━━━ 10/61 [pyyaml]
    Uninstalling Pygments-2.20.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/61 [pyyaml]
      Successfully uninstalled Pygments-2.20.0━━━━━━━━━━━━━━━━ 10/61 [pyyaml]
  Attempting uninstall: psutil[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]
    Found existing installation: psutil 5.9.8━━━━━━━━━━━━━━━━━ 11/61 [pygments]
    Uninstalling psutil-5.9.8:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]
      Successfully uninstalled psutil-5.9.8━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]
  Attempting uninstall: protobuf0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/61 [psutil]
    Found existing installation: protobuf 6.31.1━━━━━━━━━━━━━━ 12/61 [psutil]
    Uninstalling protobuf-6.31.1:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/61 [psutil]
      Successfully uninstalled protobuf-6.31.1━━━━━━━━━━━━━━━━ 12/61 [psutil]
  Attempting uninstall: platformdirs━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
    Found existing installation: platformdirs 4.10.0━━━━━━━━━━ 13/61 [protobuf]
    Uninstalling platformdirs-4.10.0:━━━━━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
      Successfully uninstalled platformdirs-4.10.0━━━━━━━━━━━━ 13/61 [protobuf]
  Attempting uninstall: packaging[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/61 [platformdirs]
    Found existing installation: packaging 25.0━━━━━━━━━━━━━━━ 16/61 [platformdirs]
    Uninstalling packaging-25.0:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/61 [platformdirs]
      Successfully uninstalled packaging-25.0━━━━━━━━━━━━━━━━━ 16/61 [platformdirs]
  Attempting uninstall: numpy[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/61 [platformdirs]
    Found existing installation: numpy 1.26.4━━━━━━━━━━━━━━━━━ 16/61 [platformdirs]
    Uninstalling numpy-1.26.4:90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16/61 [platformdirs]
      Successfully uninstalled numpy-1.26.4━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]rs]
  Attempting uninstall: mock╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Found existing installation: mock 4.0.3━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Uninstalling mock-4.0.3:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]

In [1]:
import sagemaker

print("Version:", sagemaker.__version__)
print("Has Session:", hasattr(sagemaker, "Session"))

sagemaker.config INFO - Fetched defaults config from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
Version: 2.257.3
Has Session: True

In [2]:
import boto3
import sagemaker
import pandas as pd
import numpy as np

sess = sagemaker.Session()
bucket = "rav-churn-prediction-2026"
region = sess.boto_region_name

print("Bucket:", bucket)
print("Region:", region)

sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
Bucket: rav-churn-prediction-2026
Region: us-east-2

In [3]:
s3 = boto3.client("s3")

response = s3.list_objects_v2(Bucket=bucket)

for obj in response["Contents"]:
    print(obj["Key"])

storedata_total.csv
storedata_total.xlsx

In [4]:
import pandas as pd

file_path = f"s3://{bucket}/storedata_total.csv"

df = pd.read_csv(file_path)

print("Dataset loaded successfully!")
print(df.shape)

df.head()

Dataset loaded successfully!
(30801, 15)

,custid,retained,created,firstorder,lastorder,esent,eopenrate,eclickrate,avgorder,ordfreq,paperless,refill,doorstep,favday,city
0,6H6T6N,0,9/28/12,8/11/13,8/11/13,29,100.000000,3.448276,14.52,0.000000,0,0,0,Monday,DEL
1,APCENR,1,12/19/10,4/1/11,1/19/14,95,92.631579,10.526316,83.69,0.181641,1,1,1,Friday,DEL
2,7UP6MS,0,10/3/10,12/1/10,7/6/11,0,0.000000,0.000000,33.58,0.059908,0,0,0,Wednesday,DEL
3,7ZEW8G,0,10/22/10,3/28/11,3/28/11,0,0.000000,0.000000,54.96,0.000000,0,0,0,Thursday,BOM
4,8V726M,1,11/27/10,11/29/10,1/28/13,30,90.000000,13.333333,111.91,0.008850,0,0,0,Monday,BOM

In [5]:
ImportError: Install s3fs

╭──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ ImportError: Install s3fs                                                                        │
│                      ▲                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
SyntaxError: invalid syntax

In [6]:
%pip install s3fs

Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (2026.3.0)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /opt/conda/lib/python3.12/site-packages (from s3fs) (3.7.0)
Requirement already satisfied: fsspec==2026.3.0 in /opt/conda/lib/python3.12/site-packages (from s3fs) (2026.3.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0 in /opt/conda/lib/python3.12/site-packages (from s3fs) (3.14.1)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (0.13.0)
Collecting botocore<1.43.1,>=1.42.90 (from aiobotocore<4.0.0,>=2.19.0->s3fs)
  Downloading botocore-1.43.0-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (2.9.0.post0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (1.1.0)
Requirement already satisfied: multidict<7.0.0,>=6.0.0 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (6.7.1)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs) (1.17.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (1.8.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (4.16.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (1.24.2)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.1,>=1.42.90->aiobotocore<4.0.0,>=2.19.0->s3fs) (2.7.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->aiobotocore<4.0.0,>=2.19.0->s3fs) (1.17.0)
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.12/site-packages (from yarl<2.0,>=1.17.0->aiohttp!=4.0.0a0,!=4.0.0a1,>=3.9.0->s3fs) (3.18)
Downloading botocore-1.43.0-py3-none-any.whl (15.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.0/15.0 MB 92.8 MB/s  0:00:00
Installing collected packages: botocore
  Attempting uninstall: botocore
    Found existing installation: botocore 1.43.40
    Uninstalling botocore-1.43.40:
      Successfully uninstalled botocore-1.43.40
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
amazon-sagemaker-sql-editor 0.2.5 requires rpds-py==0.27.1, but you have rpds-py 2026.6.3 which is incompatible.
amazon-sagemaker-sql-magic 0.1.4 requires numpy<2, but you have numpy 2.5.0 which is incompatible.
sagemaker-studio 1.1.22 requires numpy<2.3.0,>=1.26.4, but you have numpy 2.5.0 which is incompatible.
sagemaker-studio 1.1.22 requires pandas<3.0.0,>=2.3.2, but you have pandas 3.0.3 which is incompatible.
sagemaker-studio-analytics-extension 0.3.0 requires sparkmagic==0.22.0, but you have sparkmagic 0.21.0 which is incompatible.
snowflake-connector-python 3.17.4 requires cffi<2.0.0,>=1.9, but you have cffi 2.0.0 which is incompatible.
boto3 1.43.40 requires botocore<1.44.0,>=1.43.40, but you have botocore 1.43.0 which is incompatible.
Successfully installed botocore-1.43.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

file_path = f"s3://{bucket}/storedata_total.csv"
print(file_path)
df.info()
df.describe()
df.isnull().sum()

NameError: name 'bucket' is not defined

In [4]:
import boto3
import sagemaker
import pandas as pd
import numpy as np

ImportError: cannot import name 'DocumentModifiedShape' from 'botocore.docs.utils' (/opt/conda/lib/python3.12/site-packages/botocore/docs/utils.py)

In [7]:
%pip install --upgrade --force-reinstall boto3 botocore s3transfer "sagemaker<3"

Collecting boto3
  Using cached boto3-1.43.40-py3-none-any.whl.metadata (6.6 kB)
Collecting botocore
  Using cached botocore-1.43.40-py3-none-any.whl.metadata (5.6 kB)
Collecting s3transfer
  Using cached s3transfer-0.19.0-py3-none-any.whl.metadata (1.7 kB)
Collecting sagemaker<3
  Using cached sagemaker-2.257.3-py3-none-any.whl.metadata (17 kB)
Collecting attrs<26,>=24 (from sagemaker<3)
  Using cached attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting cloudpickle>=2.2.1 (from sagemaker<3)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Collecting docker (from sagemaker<3)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting fastapi (from sagemaker<3)
  Using cached fastapi-0.139.0-py3-none-any.whl.metadata (26 kB)
Collecting google-pasta (from sagemaker<3)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting graphene<4,>=3 (from sagemaker<3)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting importlib-metadata<7.0,>=1.4.0 (from sagemaker<3)
  Using cached importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)
Collecting jsonschema (from sagemaker<3)
  Using cached jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting numpy<3.0,>=1.26.4 (from sagemaker<3)
  Using cached numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting omegaconf<3,>=2.2 (from sagemaker<3)
  Using cached omegaconf-2.3.1-py3-none-any.whl.metadata (4.5 kB)
Collecting packaging<25,>=23.0 (from sagemaker<3)
  Using cached packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pandas>=2.3.0 (from sagemaker<3)
  Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting pathos (from sagemaker<3)
  Using cached pathos-0.3.5-py3-none-any.whl.metadata (11 kB)
Collecting platformdirs (from sagemaker<3)
  Using cached platformdirs-4.10.0-py3-none-any.whl.metadata (5.5 kB)
Collecting protobuf<7.0,>=3.12 (from sagemaker<3)
  Using cached protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Collecting psutil (from sagemaker<3)
  Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Collecting pyyaml>=6.0.1 (from sagemaker<3)
  Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting requests (from sagemaker<3)
  Using cached requests-2.34.2-py3-none-any.whl.metadata (4.8 kB)
Collecting sagemaker-core<2.0.0,>=1.0.71 (from sagemaker<3)
  Using cached sagemaker_core-1.0.78-py3-none-any.whl.metadata (4.9 kB)
Collecting schema (from sagemaker<3)
  Using cached schema-0.7.8-py2.py3-none-any.whl.metadata (34 kB)
Collecting smdebug-rulesconfig==1.0.1 (from sagemaker<3)
  Using cached smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl.metadata (943 bytes)
Collecting tblib<4,>=1.7.0 (from sagemaker<3)
  Using cached tblib-3.2.2-py3-none-any.whl.metadata (27 kB)
Collecting tqdm (from sagemaker<3)
  Using cached tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Collecting urllib3<3.0.0,>=1.26.8 (from sagemaker<3)
  Using cached urllib3-2.7.0-py3-none-any.whl.metadata (6.9 kB)
Collecting uvicorn (from sagemaker<3)
  Using cached uvicorn-0.49.0-py3-none-any.whl.metadata (6.7 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3)
  Using cached jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3)
  Using cached graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4,>=3->sagemaker<3)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Collecting typing-extensions<5,>=4.7.1 (from graphene<4,>=3->sagemaker<3)
  Using cached typing_extensions-4.16.0-py3-none-any.whl.metadata (3.3 kB)
Collecting zipp>=0.5 (from importlib-metadata<7.0,>=1.4.0->sagemaker<3)
  Using cached zipp-4.1.0-py3-none-any.whl.metadata (3.6 kB)
Collecting antlr4-python3-runtime==4.9.* (from omegaconf<3,>=2.2->sagemaker<3)
  Using cached antlr4_python3_runtime-4.9.3-py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore)
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting pydantic<3.0.0,>=2.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting rich<15.0.0,>=13.0.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached rich-14.3.4-py3-none-any.whl.metadata (18 kB)
Collecting mock<5.0,>4.0 (from sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached mock-4.0.3-py3-none-any.whl.metadata (2.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema->sagemaker<3)
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema->sagemaker<3)
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema->sagemaker<3)
  Using cached rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached pygments-2.20.0-py3-none-any.whl.metadata (2.5 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<2.0.0,>=1.0.71->sagemaker<3)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting charset_normalizer<4,>=2 (from requests->sagemaker<3)
  Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Collecting idna<4,>=2.5 (from requests->sagemaker<3)
  Using cached idna-3.18-py3-none-any.whl.metadata (6.1 kB)
Collecting certifi>=2023.5.7 (from requests->sagemaker<3)
  Using cached certifi-2026.6.17-py3-none-any.whl.metadata (2.5 kB)
Collecting starlette>=0.46.0 (from fastapi->sagemaker<3)
  Using cached starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting annotated-doc>=0.0.2 (from fastapi->sagemaker<3)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting anyio<5,>=3.6.2 (from starlette>=0.46.0->fastapi->sagemaker<3)
  Using cached anyio-4.14.1-py3-none-any.whl.metadata (4.6 kB)
Collecting ppft>=1.7.8 (from pathos->sagemaker<3)
  Using cached ppft-1.7.8-py3-none-any.whl.metadata (12 kB)
Collecting dill>=0.4.1 (from pathos->sagemaker<3)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pox>=0.3.7 (from pathos->sagemaker<3)
  Using cached pox-0.3.7-py3-none-any.whl.metadata (8.0 kB)
Collecting multiprocess>=0.70.19 (from pathos->sagemaker<3)
  Using cached multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting click>=7.0 (from uvicorn->sagemaker<3)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting h11>=0.8 (from uvicorn->sagemaker<3)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Using cached sagemaker-2.257.3-py3-none-any.whl (1.7 MB)
Using cached smdebug_rulesconfig-1.0.1-py2.py3-none-any.whl (20 kB)
Using cached boto3-1.43.40-py3-none-any.whl (140 kB)
Using cached botocore-1.43.40-py3-none-any.whl (15.3 MB)
Using cached s3transfer-0.19.0-py3-none-any.whl (90 kB)
Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_core-3.2.11-py3-none-any.whl (214 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached importlib_metadata-6.11.0-py3-none-any.whl (23 kB)
Using cached jmespath-1.1.0-py3-none-any.whl (20 kB)
Using cached numpy-2.5.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.7 MB)
Using cached omegaconf-2.3.1-py3-none-any.whl (79 kB)
Using cached packaging-24.2-py3-none-any.whl (65 kB)
Using cached protobuf-6.33.6-cp39-abi3-manylinux2014_x86_64.whl (323 kB)
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached sagemaker_core-1.0.78-py3-none-any.whl (444 kB)
Using cached jsonschema-4.26.0-py3-none-any.whl (90 kB)
Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Using cached platformdirs-4.10.0-py3-none-any.whl (22 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached pyyaml-6.0.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (807 kB)
Using cached rich-14.3.4-py3-none-any.whl (310 kB)
Using cached pygments-2.20.0-py3-none-any.whl (1.2 MB)
Using cached tblib-3.2.2-py3-none-any.whl (12 kB)
Using cached typing_extensions-4.16.0-py3-none-any.whl (45 kB)
Using cached urllib3-2.7.0-py3-none-any.whl (131 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Using cached rpds_py-2026.6.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (366 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached zipp-4.1.0-py3-none-any.whl (10 kB)
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached requests-2.34.2-py3-none-any.whl (73 kB)
Using cached charset_normalizer-3.4.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (216 kB)
Using cached idna-3.18-py3-none-any.whl (65 kB)
Using cached certifi-2026.6.17-py3-none-any.whl (133 kB)
Using cached fastapi-0.139.0-py3-none-any.whl (130 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached starlette-1.3.1-py3-none-any.whl (73 kB)
Using cached anyio-4.14.1-py3-none-any.whl (124 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Using cached pathos-0.3.5-py3-none-any.whl (82 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached multiprocess-0.70.19-py312-none-any.whl (150 kB)
Using cached pox-0.3.7-py3-none-any.whl (29 kB)
Using cached ppft-1.7.8-py3-none-any.whl (56 kB)
Using cached psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
Using cached schema-0.7.8-py2.py3-none-any.whl (19 kB)
Using cached tqdm-4.68.3-py3-none-any.whl (78 kB)
Using cached uvicorn-0.49.0-py3-none-any.whl (71 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: schema, antlr4-python3-runtime, zipp, urllib3, typing-extensions, tqdm, tblib, smdebug-rulesconfig, six, rpds-py, pyyaml, pygments, psutil, protobuf, ppft, pox, platformdirs, packaging, numpy, mock, mdurl, jmespath, idna, h11, graphql-core, dill, cloudpickle, click, charset_normalizer, certifi, attrs, annotated-types, annotated-doc, uvicorn, typing-inspection, requests, referencing, python-dateutil, pydantic-core, omegaconf, multiprocess, markdown-it-py, importlib-metadata, graphql-relay, google-pasta, anyio, starlette, rich, pydantic, pathos, pandas, jsonschema-specifications, graphene, docker, botocore, s3transfer, jsonschema, fastapi, boto3, sagemaker-core, sagemaker
  Attempting uninstall: schema
    Found existing installation: schema 0.7.8
    Uninstalling schema-0.7.8:
      Successfully uninstalled schema-0.7.8
  Attempting uninstall: antlr4-python3-runtime
    Found existing installation: antlr4-python3-runtime 4.9.3
    Uninstalling antlr4-python3-runtime-4.9.3:
      Successfully uninstalled antlr4-python3-runtime-4.9.3
  Attempting uninstall: zipp━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
    Found existing installation: zipp 4.1.0━━━━━━━━━━  1/61 [antlr4-python3-runtime]
    Uninstalling zipp-4.1.0:━━━━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
      Successfully uninstalled zipp-4.1.0━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
  Attempting uninstall: urllib3━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
    Found existing installation: urllib3 2.7.0━━━━━━━  1/61 [antlr4-python3-runtime]
    Uninstalling urllib3-2.7.0:━━━━━━━━━━━━━━━━━━━━━━  1/61 [antlr4-python3-runtime]
      Successfully uninstalled urllib3-2.7.0━━━━━━━━━  1/61 [antlr4-python3-runtime]
  Attempting uninstall: typing-extensions━━━━━━━━━━━━━━━━━━━━━━━━━  3/61 [urllib3]e]
    Found existing installation: typing_extensions 4.16.0━━━━━  3/61 [urllib3]
    Uninstalling typing_extensions-4.16.0:━━━━━━━━━━━━━━━━━━━━  3/61 [urllib3]
      Successfully uninstalled typing_extensions-4.16.0━━━━━━━━━━━  4/61 [typing-extensions]
  Attempting uninstall: tqdm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  4/61 [typing-extensions]
    Found existing installation: tqdm 4.68.3━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]tensions]
    Uninstalling tqdm-4.68.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
      Successfully uninstalled tqdm-4.68.3━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
  Attempting uninstall: tblib━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
    Found existing installation: tblib 3.2.2━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
    Uninstalling tblib-3.2.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
      Successfully uninstalled tblib-3.2.2━━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
  Attempting uninstall: smdebug-rulesconfig━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
    Found existing installation: smdebug-rulesconfig 1.0.1━━━━  5/61 [tqdm]
    Uninstalling smdebug-rulesconfig-1.0.1:━━━━━━━━━━━━━━━━━━━  5/61 [tqdm]
      Successfully uninstalled smdebug-rulesconfig-1.0.1━━━━━━  5/61 [tqdm]
  Attempting uninstall: six[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/61 [smdebug-rulesconfig]
    Found existing installation: six 1.17.0━━━━━━━━━━━━━━━━━━━  7/61 [smdebug-rulesconfig]
    Uninstalling six-1.17.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  7/61 [smdebug-rulesconfig]
      Successfully uninstalled six-1.17.0━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]rulesconfig]
  Attempting uninstall: rpds-py━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
    Found existing installation: rpds-py 2026.6.3━━━━━━━━━━━━━  8/61 [six]
    Uninstalling rpds-py-2026.6.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
      Successfully uninstalled rpds-py-2026.6.3━━━━━━━━━━━━━━━  8/61 [six]
  Attempting uninstall: pyyaml━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
    Found existing installation: PyYAML 6.0.3━━━━━━━━━━━━━━━━━  8/61 [six]
    Uninstalling PyYAML-6.0.3:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  8/61 [six]
      Successfully uninstalled PyYAML-6.0.3━━━━━━━━━━━━━━━━━━━  8/61 [six]
  Attempting uninstall: pygmentsm━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/61 [pyyaml]
    Found existing installation: Pygments 2.20.0━━━━━━━━━━━━━━ 10/61 [pyyaml]
    Uninstalling Pygments-2.20.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/61 [pyyaml]
      Successfully uninstalled Pygments-2.20.0━━━━━━━━━━━━━━━━ 10/61 [pyyaml]
  Attempting uninstall: psutil[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]
    Found existing installation: psutil 7.2.2━━━━━━━━━━━━━━━━━ 11/61 [pygments]
    Uninstalling psutil-7.2.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]
      Successfully uninstalled psutil-7.2.2━━━━━━━━━━━━━━━━━━━ 11/61 [pygments]
  Attempting uninstall: protobuf0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/61 [psutil]
    Found existing installation: protobuf 6.33.6━━━━━━━━━━━━━━ 12/61 [psutil]
    Uninstalling protobuf-6.33.6:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12/61 [psutil]
      Successfully uninstalled protobuf-6.33.6━━━━━━━━━━━━━━━━ 12/61 [psutil]
  Attempting uninstall: ppft0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
    Found existing installation: ppft 1.7.8━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
    Uninstalling ppft-1.7.8:90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
      Successfully uninstalled ppft-1.7.8━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
  Attempting uninstall: pox[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
    Found existing installation: pox 0.3.7━━━━━━━━━━━━━━━━━━━━ 13/61 [protobuf]
    Uninstalling pox-0.3.7:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/61 [pox]]
      Successfully uninstalled pox-0.3.7━━━━━━━━━━━━━━━━━━━━━━ 15/61 [pox]
  Attempting uninstall: platformdirs━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/61 [pox]
    Found existing installation: platformdirs 4.10.0━━━━━━━━━━ 15/61 [pox]
    Uninstalling platformdirs-4.10.0:━━━━━━━━━━━━━━━━━━━━━━━━━ 15/61 [pox]
      Successfully uninstalled platformdirs-4.10.0━━━━━━━━━━━━ 15/61 [pox]
  Attempting uninstall: packaging━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/61 [pox]
    Found existing installation: packaging 24.2━━━━━━━━━━━━━━━ 15/61 [pox]
    Uninstalling packaging-24.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/61 [pox]
      Successfully uninstalled packaging-24.2━━━━━━━━━━━━━━━━━ 15/61 [pox]
  Attempting uninstall: numpy━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/61 [packaging]
    Found existing installation: numpy 2.5.0━━━━━━━━━━━━━━━━━━ 17/61 [packaging]
    Uninstalling numpy-2.5.0:━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17/61 [packaging]
      Successfully uninstalled numpy-2.5.0━━━━━━━━━━━━━━━━━━━━ 17/61 [packaging]
  Attempting uninstall: mock╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Found existing installation: mock 4.0.3━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Uninstalling mock-4.0.3:m━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
      Successfully uninstalled mock-4.0.3━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
  Attempting uninstall: mdurl━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Found existing installation: mdurl 0.1.2━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Uninstalling mdurl-0.1.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
      Successfully uninstalled mdurl-0.1.2━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
  Attempting uninstall: jmespath0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Found existing installation: jmespath 1.1.0━━━━━━━━━━━━━━━ 18/61 [numpy]
    Uninstalling jmespath-1.1.0:0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
      Successfully uninstalled jmespath-1.1.0━━━━━━━━━━━━━━━━━ 18/61 [numpy]
  Attempting uninstall: idnam━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18/61 [numpy]
    Found existing installation: idna 3.18━━━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
    Uninstalling idna-3.18:╺━━━━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
      Successfully uninstalled idna-3.18━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
  Attempting uninstall: h11╺━━━━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
    Found existing installation: h11 0.16.0━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
    Uninstalling h11-0.16.0:━━━━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
      Successfully uninstalled h11-0.16.0━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
  Attempting uninstall: graphql-corem━━━━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
    Found existing installation: graphql-core 3.2.11━━━━━━━━━━ 22/61 [idna]
    Uninstalling graphql-core-3.2.11:━━━━━━━━━━━━━━━━━━━━━━━━━ 22/61 [idna]
      Successfully uninstalled graphql-core-3.2.11━━━━━━━━━━━━ 22/61 [idna]

In [1]:
import boto3
import botocore
import sagemaker

print("boto3:", boto3.__version__)
print("botocore:", botocore.__version__)
print("sagemaker:", sagemaker.__version__)
print("Has Session:", hasattr(sagemaker, "Session"))

sagemaker.config INFO - Fetched defaults config from location: /etc/xdg/sagemaker/config.yaml
sagemaker.config INFO - Not applying SDK defaults from location: /home/sagemaker-user/.config/sagemaker/config.yaml
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
boto3: 1.43.40
botocore: 1.43.40
sagemaker: 2.257.3
Has Session: True

In [2]:
import pandas as pd
import numpy as np

sess = sagemaker.Session()
bucket = "rav-churn-prediction-2026"
region = sess.boto_region_name

file_path = f"s3://{bucket}/storedata_total.csv"
df = pd.read_csv(file_path)

print(df.shape)
df.head()

sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
(30801, 15)

,custid,retained,created,firstorder,lastorder,esent,eopenrate,eclickrate,avgorder,ordfreq,paperless,refill,doorstep,favday,city
0,6H6T6N,0,9/28/12,8/11/13,8/11/13,29,100.000000,3.448276,14.52,0.000000,0,0,0,Monday,DEL
1,APCENR,1,12/19/10,4/1/11,1/19/14,95,92.631579,10.526316,83.69,0.181641,1,1,1,Friday,DEL
2,7UP6MS,0,10/3/10,12/1/10,7/6/11,0,0.000000,0.000000,33.58,0.059908,0,0,0,Wednesday,DEL
3,7ZEW8G,0,10/22/10,3/28/11,3/28/11,0,0.000000,0.000000,54.96,0.000000,0,0,0,Thursday,BOM
4,8V726M,1,11/27/10,11/29/10,1/28/13,30,90.000000,13.333333,111.91,0.008850,0,0,0,Monday,BOM

In [3]:
df["firstorder"] = pd.to_datetime(df["firstorder"], errors="coerce")
df["lastorder"] = pd.to_datetime(df["lastorder"], errors="coerce")
df["created"] = pd.to_datetime(df["created"], errors="coerce")

df = df.dropna()

df["first_last_days_diff"] = (df["lastorder"] - df["firstorder"]).dt.days
df["created_first_days_diff"] = (df["created"] - df["firstorder"]).dt.days

df = df.drop(["custid", "created", "firstorder", "lastorder"], axis=1)

df = pd.get_dummies(df, columns=["favday", "city"], prefix=["favday", "city"])

print("Preprocessing done")
print(df.shape)
df.head()

Preprocessing done
(30758, 22)

,retained,esent,eopenrate,eclickrate,avgorder,ordfreq,paperless,refill,doorstep,first_last_days_diff,...,favday_Monday,favday_Saturday,favday_Sunday,favday_Thursday,favday_Tuesday,favday_Wednesday,city_BLR,city_BOM,city_DEL,city_MAA
0,0,29,100.000000,3.448276,14.52,0.000000,0,0,0,0,...,True,False,False,False,False,False,False,False,True,False
1,1,95,92.631579,10.526316,83.69,0.181641,1,1,1,1024,...,False,False,False,False,False,False,False,False,True,False
2,0,0,0.000000,0.000000,33.58,0.059908,0,0,0,217,...,False,False,False,False,False,True,False,False,True,False
3,0,0,0.000000,0.000000,54.96,0.000000,0,0,0,0,...,False,False,False,True,False,False,False,True,False,False
4,1,30,90.000000,13.333333,111.91,0.008850,0,0,0,791,...,True,False,False,False,False,False,False,True,False,False

In [4]:
from sklearn.model_selection import train_test_split

# Features
X = df.drop("retained", axis=1)

# Target
y = df["retained"]

# Train (80%) and Temp (20%)
X_train, X_temp, y_train, y_temp = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Validation (10%) and Test (10%)
X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42,
    stratify=y_temp
)

print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Testing:", X_test.shape)

Training: (24606, 21)
Validation: (3076, 21)
Testing: (3076, 21)

In [5]:
train = pd.concat([y_train, X_train], axis=1)
validation = pd.concat([y_val, X_val], axis=1)
test = pd.concat([y_test, X_test], axis=1)

train.to_csv("train.csv", index=False, header=False)
validation.to_csv("validation.csv", index=False, header=False)
test.to_csv("test.csv", index=False)

print("Files created successfully!")

Files created successfully!

In [6]:
import boto3

s3 = boto3.client("s3")

s3.upload_file("train.csv", bucket, "data/train/train.csv")
s3.upload_file("validation.csv", bucket, "data/validation/validation.csv")
s3.upload_file("test.csv", bucket, "data/test/test.csv")

print("Train, validation, and test files uploaded to S3 successfully!")

Train, validation, and test files uploaded to S3 successfully!

In [7]:
response = s3.list_objects_v2(Bucket=bucket, Prefix="data/")

for obj in response["Contents"]:
    print(obj["Key"])

data/test/test.csv
data/train/train.csv
data/validation/validation.csv

In [8]:
import sagemaker
from sagemaker import image_uris

sess = sagemaker.Session()

role = sagemaker.get_execution_role()

print(role)

sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3Bucket
sagemaker.config INFO - Applied value from config key = SageMaker.PythonSDK.Modules.Session.DefaultS3ObjectKeyPrefix
arn:aws:iam::863576956119:role/service-role/AmazonSageMakerAdminIAMExecutionRole

In [9]:
from sagemaker.estimator import Estimator
from sagemaker.image_uris import retrieve

container = retrieve(
    framework="xgboost",
    region=region,
    version="1.7-1"
)

xgb = Estimator(
    image_uri=container,
    role=role,
    instance_count=1,
    instance_type="ml.m5.large",
    output_path=f"s3://{bucket}/output",
    sagemaker_session=sess
)

xgb.set_hyperparameters(
    objective="binary:logistic",
    num_round=100,
    max_depth=5,
    eta=0.2,
    subsample=0.8,
    eval_metric="auc"
)

sagemaker.config INFO - Applied value from config key = SageMaker.TrainingJob.Environment

In [10]:
from sagemaker.inputs import TrainingInput

train_input = TrainingInput(
    f"s3://{bucket}/data/train/",
    content_type="text/csv"
)

validation_input = TrainingInput(
    f"s3://{bucket}/data/validation/",
    content_type="text/csv"
)

xgb.fit(
    {
        "train": train_input,
        "validation": validation_input
    }
)

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:13                                                                                   │
│                                                                                                  │
│   10 │   content_type="text/csv"                                                                 │
│   11 )                                                                                           │
│   12                                                                                             │
│ ❱ 13 xgb.fit(                                                                                    │
│   14 │   {                                                                                       │
│   15 │   │   "train": train_input,                                                               │
│   16 │   │   "validation": validation_input                                                      │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/telemetry/telemetry_logging.py:171 in wrapper  │
│                                                                                                  │
│   168 │   │   │   │   │   caught_ex = e                                                          │
│   169 │   │   │   │   finally:                                                                   │
│   170 │   │   │   │   │   if caught_ex:                                                          │
│ ❱ 171 │   │   │   │   │   │   raise caught_ex                                                    │
│   172 │   │   │   │   │   return response  # pylint: disable=W0150                               │
│   173 │   │   │   else:                                                                          │
│   174 │   │   │   │   logger.debug(                                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/telemetry/telemetry_logging.py:142 in wrapper  │
│                                                                                                  │
│   139 │   │   │   │   start_timer = perf_counter()                                               │
│   140 │   │   │   │   try:                                                                       │
│   141 │   │   │   │   │   # Call the original function                                           │
│ ❱ 142 │   │   │   │   │   response = func(*args, **kwargs)                                       │
│   143 │   │   │   │   │   stop_timer = perf_counter()                                            │
│   144 │   │   │   │   │   elapsed = stop_timer - start_timer                                     │
│   145 │   │   │   │   │   extra += f"&x-latency={round(elapsed, 2)}"                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/workflow/pipeline_context.py:346 in wrapper    │
│                                                                                                  │
│   343 │   │   │                                                                                  │
│   344 │   │   │   return _StepArguments(retrieve_caller_name(self_instance), run_func, *args,    │
│   345 │   │                                                                                      │
│ ❱ 346 │   │   return run_func(*args, **kwargs)                                                   │
│   347 │                                                                                          │
│   348 │   return wrapper                                                                         │
│   349                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/estimator.py:1425 in fit                       │
│                                                                                                  │
│   1422 │   │   self._prepare_for_training(job_name=job_name)                                     │
│   1423 │   │                                                                                     │
│   1424 │   │   experiment_config = check_and_get_run_experiment_config(experiment_config)        │
│ ❱ 1425 │   │   self.latest_training_job = _TrainingJob.start_new(self, inputs, experiment_confi  │
│   1426 │   │   self.jobs.append(self.latest_training_job)                                        │
│   1427 │   │   forward_to_mlflow_tracking_server = False                                         │
│   1428 │   │   if os.environ.get("MLFLOW_TRACKING_URI") and self.enable_network_isolation():     │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/estimator.py:2578 in start_new                 │
│                                                                                                  │
│   2575 │   │   train_args = cls._get_train_args(estimator, inputs, experiment_config)            │
│   2576 │   │                                                                                     │
│   2577 │   │   logger.debug("Train args after processing defaults: %s", train_args)              │
│ ❱ 2578 │   │   estimator.sagemaker_session.train(**train_args)                                   │
│   2579 │   │                                                                                     │
│   2580 │   │   return cls(estimator.sagemaker_session, estimator._current_job_name)              │
│   2581                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:1383 in train                       │
│                                                                                                  │
│   1380 │   │   │   │   )                                                                         │
│   1381 │   │   │   │   raise e                                                                   │
│   1382 │   │                                                                                     │
│ ❱ 1383 │   │   self._intercept_create_request(train_request, submit, self.train.__name__)        │
│   1384 │                                                                                         │
│   1385 │   def _get_train_request(  # noqa: C901                                                 │
│   1386 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:7151 in _intercept_create_request   │
│                                                                                                  │
│   7148 │   │   │   create (functor): a functor calls the sagemaker client create method          │
│   7149 │   │   │   func_name (str): the name of the function needed intercepting                 │
│   7150 │   │   """                                                                               │
│ ❱ 7151 │   │   return create(request)                                                            │
│   7152 │                                                                                         │
│   7153 │   def _create_inference_recommendations_job_request(                                    │
│   7154 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:1381 in submit                      │
│                                                                                                  │
│   1378 │   │   │   │   logger.error(                                                             │
│   1379 │   │   │   │   │   "Please check the troubleshooting guide for common errors: %s", trou  │
│   1380 │   │   │   │   )                                                                         │
│ ❱ 1381 │   │   │   │   raise e                                                                   │
│   1382 │   │                                                                                     │
│   1383 │   │   self._intercept_create_request(train_request, submit, self.train.__name__)        │
│   1384                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/sagemaker/session.py:1372 in submit                      │
│                                                                                                  │
│   1369 │   │   │   try:                                                                          │
│   1370 │   │   │   │   logger.info("Creating training-job with name: %s", job_name)              │
│   1371 │   │   │   │   logger.debug("train request: %s", json.dumps(request, indent=4))          │
│ ❱ 1372 │   │   │   │   self.sagemaker_client.create_training_job(**request)                      │
│   1373 │   │   │   except Exception as e:                                                        │
│   1374 │   │   │   │   troubleshooting = (                                                       │
│   1375 │   │   │   │   │   "https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-python-sd  │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/client.py:606 in _api_call                      │
│                                                                                                  │
│    603 │   │   │   │   │   f"{py_operation_name}() only accepts keyword arguments."              │
│    604 │   │   │   │   )                                                                         │
│    605 │   │   │   # The "self" in this scope is referring to the BaseClient.                    │
│ ❱  606 │   │   │   return self._make_api_call(operation_name, kwargs)                            │
│    607 │   │                                                                                     │
│    608 │   │   _api_call.__name__ = str(py_operation_name)                                       │
│    609                                                                                           │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/context.py:123 in wrapper                       │
│                                                                                                  │
│   120 │   │   │   with start_as_current_context():                                               │
│   121 │   │   │   │   if hook:                                                                   │
│   122 │   │   │   │   │   hook()                                                                 │
│ ❱ 123 │   │   │   │   return func(*args, **kwargs)                                               │
│   124 │   │                                                                                      │
│   125 │   │   return wrapper                                                                     │
│   126                                                                                            │
│                                                                                                  │
│ /opt/conda/lib/python3.12/site-packages/botocore/client.py:1094 in _make_api_call                │
│                                                                                                  │
│   1091 │   │   │   │   'error_code_override'                                                     │
│   1092 │   │   │   ) or error_info.get("Code")                                                   │
│   1093 │   │   │   error_class = self.exceptions.from_code(error_code)                           │
│ ❱ 1094 │   │   │   raise error_class(parsed_response, operation_name)                            │
│   1095 │   │   else:                                                                             │
│   1096 │   │   │   return parsed_response                                                        │
│   1097                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ResourceLimitExceeded: An error occurred (ResourceLimitExceeded) when calling the CreateTrainingJob operation: The
account-level service limit 'ml.m5.large for training job usage' is 0 Instances, with current utilization of 0
Instances and a request delta of 1 Instances. Please use AWS Service Quotas to request an increase for this quota.
If AWS Service Quotas is not available, contact AWS support to request an increase for this quota.

In [12]:
instance_type="ml.m5.large"

In [13]:
instance_type="ml.t3.medium"